apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: vote-api-image
  namespace: vote
spec:
  type: image
  params:
  - name: url
    value: index.docker.io/tahirahmed521/vote-api:latest
