apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote-sa
  namespace: vote
secrets:
  - name: basic-user-pass-docker
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test
  namespace: vote
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "delete", "patch", "create"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "delete", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test
  namespace: vote
subjects:
  - kind: ServiceAccount
    name: vote-sa
roleRef:
  kind: Role
  name: test
  apiGroup: rbac.authorization.k8s.io