apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: vote
spec:
  resources:
  - name: my-source-repo
    type: git
  - name: my-image-resource
    type: image
  params:
  - name: deployment-name
    description: name of the deployment to be patched
  tasks:
  - name: create-upate-deployment
    taskRef:
      name: build-docker-image-task
    resources:
      inputs:
      - name: k8s-yamls-repo
        resource: my-source-repo
      - name: new-image
        resource: my-image-resource
      outputs:
        - name: builtImage
          resource: my-image-resource
    params:
    - name: deployment-name
      value: $(params.deployment-name)
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: /workspace/k8s-yamls-repo
    - name: destination
      value: index.docker.io/tahirahmed521/vote-api:latest

